{% set version = "1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pegas
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pegas_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pegas/pegas_{{ version }}.tar.gz
  sha256: 103eb2b29d70e71315809421abdf6f2e8ada9c466469c6e3e7cc0314b9cd3dc8

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-adegenet                 # [build_platform != target_platform]
    - r-ape >=2.4                # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-adegenet
    - r-ape >=2.4
  run:
    - r-base
    - r-adegenet
    - r-ape >=2.4

test:
  commands:
    - $R -e "library('pegas')"           # [not win]
    - "\"%R%\" -e \"library('pegas')\""  # [win]

about:
  home: http://ape-package.ird.fr/pegas.html
  license: GPL-2.0-or-later
  summary: Functions for reading, writing, plotting, analysing, and manipulating allelic and haplotypic data, including from VCF files, and for the analysis of population nucleotide sequences and micro-satellites including coalescent analyses, linkage disequilibrium, population structure (Fst, Amova) and equilibrium (HWE),
    haplotype networks, minimum spanning tree and network, and median-joining networks.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pegas
# Version: 0.11
# Date: 2018-07-07
# Title: Population and Evolutionary Genetics Analysis System
# Authors@R: c(person("Emmanuel", "Paradis", role = c("aut", "cre", "cph"), email = "Emmanuel.Paradis@ird.fr"), person("Thibaut", "Jombart", role = c("aut", "cph")), person("Knaus", "Brian", role = c("aut", "cph")), person("Klaus", "Schliep", role = c("aut", "cph")), person("Alastair", "Potts", role = c("aut", "cph")), person("David", "Winter", role = c("aut", "cph")), person("Zhian N.", "Kamvar", role = c("aut", "cph")))
# Depends: R (>= 2.6.0), ape (>= 2.4), adegenet
# Imports: graphics, utils
# Suggests: rgl
# ZipData: no
# Description: Functions for reading, writing, plotting, analysing, and manipulating allelic and haplotypic data, including from VCF files, and for the analysis of population nucleotide sequences and micro-satellites including coalescent analyses, linkage disequilibrium, population structure (Fst, Amova) and equilibrium (HWE), haplotype networks, minimum spanning tree and network, and median-joining networks.
# License: GPL (>= 2)
# URL: http://ape-package.ird.fr/pegas.html
# NeedsCompilation: yes
# Packaged: 2018-07-09 09:10:12 UTC; paradis
# Author: Emmanuel Paradis [aut, cre, cph], Thibaut Jombart [aut, cph], Knaus Brian [aut, cph], Klaus Schliep [aut, cph], Alastair Potts [aut, cph], David Winter [aut, cph], Zhian N. Kamvar [aut, cph]
# Maintainer: Emmanuel Paradis <Emmanuel.Paradis@ird.fr>
# Repository: CRAN
# Date/Publication: 2018-07-09 10:30:08 UTC
