travis:
  secure:
    BINSTAR_TOKEN: sOjTE0jH9dbs0JMZj8RA3f+iV2NxZlUHfms/ryTTqVPE5sEwm2nnkKqsABjg2M4uiSbLpzSivJLe0O3F69XgrcNiMeeEub8Zx5TAuQXfXR5F5CDW/kpewd7FRtSHmyB5SzLXUneqTQ37MA2jiOXXUc8dUE/p3eaqof/iJifq3IVm/0RZ8utN1c9lF9pAfnpiITw9yIjECOF9b5KG4xWjsjM/Bk4x1g69p2EHo9xsygujEw5hXORAInGSHYfQov2H0TKAFFaN72vD1k9S9mA1dJgdycW6ZFkjW+ZtVZSVa5eOCUSJ2BWmw5H5k28EN//uGQGhrGoRfvTMN2AXn7sssAltG5H7kh8esqU7PFA2odD34Az/K9TH7qAlJC7U6a5+u58SwwxNAERRPIN6LHVn9lVeQvxIbDlEUvPPqYnswBfVjlFjHqVrYHTi8NPrTSXWjiuDKLMeQ/BE/7sBUc73aJN8qljR+YDBw6duMM0/K4qg1QMgQFu4AwwIgEg0rVUxT/Q0rt1lPHsYNTIKy2KF2aNTpMXhXMN1wRKoS4VmZ5a0YbEQEb5HwoHTjV5ixRLyQZO5LKI6VJMIs/qhDb5eNQCW7RGGOsTKvDNl45XxhsZcMwWG55DbK/lxDX2bdr6VTjvnVppnTVtbK4Bxiv0sKPoWajLxy46N1HeokhMQKPY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
